spring:
  application:
    name: config-server
  cloud:
    config:
     server:
      git:
        uri: https://github.com/zhankun/spring-cloud-config
        search-paths: config
        #username: github账号和密码，公有库可以不用填
        #password:
        strict-host-key-checking: false
server:
  port: 8009


